/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BasicSolverV1Interface extends ethers.utils.Interface {
  functions: {
    "addData(uint256,bytes)": FunctionFragment;
    "addressFromChainIndex(uint256)": FunctionFragment;
    "arbitrate(uint256,uint256[])": FunctionFragment;
    "arbitrateNull(uint256)": FunctionFragment;
    "arbitrationPending(uint256)": FunctionFragment;
    "arbitrationRequested(uint256)": FunctionFragment;
    "chainChild()": FunctionFragment;
    "chainIndex()": FunctionFragment;
    "chainParent()": FunctionFragment;
    "conditions(uint256)": FunctionFragment;
    "config()": FunctionFragment;
    "confirmPayouts(uint256)": FunctionFragment;
    "deployChild(tuple)": FunctionFragment;
    "executeSolve(uint256)": FunctionFragment;
    "getCallbackOutput(uint256)": FunctionFragment;
    "getConditions()": FunctionFragment;
    "getData(uint256)": FunctionFragment;
    "getOutgoingCallbacks(uint256)": FunctionFragment;
    "handleCallback(uint256)": FunctionFragment;
    "ingestsValid()": FunctionFragment;
    "init(address,uint256,tuple)": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "percentage(uint256,uint256,uint128)": FunctionFragment;
    "prepareSolve(uint256)": FunctionFragment;
    "proposePayouts(uint256,uint256[])": FunctionFragment;
    "redeemPosition(address,bytes32,bytes32,uint256[])": FunctionFragment;
    "registerOutgoingCallback(uint256,uint256)": FunctionFragment;
    "setTrackingId(bytes32)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "timelock()": FunctionFragment;
    "trackingId()": FunctionFragment;
    "uiURI()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addData",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addressFromChainIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrate",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrateNull",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrationPending",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrationRequested",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainChild",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chainIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chainParent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conditions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmPayouts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployChild",
    values: [
      {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCallbackOutput",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutgoingCallbacks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleCallback",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ingestsValid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [
      string,
      BigNumberish,
      {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "percentage",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareSolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposePayouts",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemPosition",
    values: [string, BytesLike, BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOutgoingCallback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrackingId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "trackingId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "uiURI", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressFromChainIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbitrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "arbitrateNull",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitrationPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitrationRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainChild", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chainIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainParent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "conditions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployChild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCallbackOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOutgoingCallbacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ingestsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "percentage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prepareSolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposePayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOutgoingCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrackingId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trackingId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "uiURI", data: BytesLike): Result;

  events: {
    "DeployedChild(address)": EventFragment;
    "PreparedSolve(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeployedChild"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PreparedSolve"): EventFragment;
}

export class BasicSolverV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BasicSolverV1Interface;

  functions: {
    addData(
      _slot: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addressFromChainIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _address: string }>;

    arbitrate(
      _index: BigNumberish,
      payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    arbitrateNull(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    arbitrationPending(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    arbitrationRequested(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    chainChild(overrides?: CallOverrides): Promise<[string]>;

    chainIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    chainParent(overrides?: CallOverrides): Promise<[string]>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, number] & {
        collateralToken: string;
        questionId: string;
        parentCollectionId: string;
        conditionId: string;
        status: number;
      }
    >;

    config(
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        string,
        [
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[],
          BigNumber[][],
          ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[]
        ] & {
          collateralToken: string;
          outcomeSlots: BigNumber;
          parentCollectionIndexSet: BigNumber;
          amountSlot: BigNumber;
          partition: BigNumber[];
          recipientAddressSlots: BigNumber[];
          recipientAmountSlots: BigNumber[][];
          outcomeURIs: ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[];
        }
      ] & {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumber;
        data: string;
        conditionBase: [
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[],
          BigNumber[][],
          ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[]
        ] & {
          collateralToken: string;
          outcomeSlots: BigNumber;
          parentCollectionIndexSet: BigNumber;
          amountSlot: BigNumber;
          partition: BigNumber[];
          recipientAddressSlots: BigNumber[];
          recipientAmountSlots: BigNumber[][];
          outcomeURIs: ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[];
        };
      }
    >;

    confirmPayouts(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployChild(
      _config: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeSolve(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCallbackOutput(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { data: string }>;

    getConditions(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string, string, BigNumber[], number] & {
          collateralToken: string;
          questionId: string;
          parentCollectionId: string;
          conditionId: string;
          payouts: BigNumber[];
          status: number;
        })[]
      ]
    >;

    getData(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { data: string }>;

    getOutgoingCallbacks(
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    handleCallback(
      _slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ingestsValid(overrides?: CallOverrides): Promise<[boolean]>;

    init(
      _chainParent: string,
      _chainIndex: BigNumberish,
      _solverConfig: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    percentage(
      x: BigNumberish,
      y: BigNumberish,
      scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    prepareSolve(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposePayouts(
      _index: BigNumberish,
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    redeemPosition(
      _collateralToken: string,
      _parentCollectionId: BytesLike,
      _conditionId: BytesLike,
      _indexSets: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerOutgoingCallback(
      _slot: BigNumberish,
      _chainIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTrackingId(
      _trackingId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    timelock(overrides?: CallOverrides): Promise<[BigNumber]>;

    trackingId(overrides?: CallOverrides): Promise<[string]>;

    uiURI(
      overrides?: CallOverrides
    ): Promise<
      [string, number, number] & {
        digest: string;
        hashFunction: number;
        size: number;
      }
    >;
  };

  addData(
    _slot: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addressFromChainIndex(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  arbitrate(
    _index: BigNumberish,
    payouts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  arbitrateNull(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  arbitrationPending(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  arbitrationRequested(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  chainChild(overrides?: CallOverrides): Promise<string>;

  chainIndex(overrides?: CallOverrides): Promise<BigNumber>;

  chainParent(overrides?: CallOverrides): Promise<string>;

  conditions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, number] & {
      collateralToken: string;
      questionId: string;
      parentCollectionId: string;
      conditionId: string;
      status: number;
    }
  >;

  config(
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      string,
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[],
        BigNumber[],
        BigNumber[][],
        ([string, number, number] & {
          digest: string;
          hashFunction: number;
          size: number;
        })[]
      ] & {
        collateralToken: string;
        outcomeSlots: BigNumber;
        parentCollectionIndexSet: BigNumber;
        amountSlot: BigNumber;
        partition: BigNumber[];
        recipientAddressSlots: BigNumber[];
        recipientAmountSlots: BigNumber[][];
        outcomeURIs: ([string, number, number] & {
          digest: string;
          hashFunction: number;
          size: number;
        })[];
      }
    ] & {
      implementation: string;
      keeper: string;
      arbitrator: string;
      timelockSeconds: BigNumber;
      data: string;
      conditionBase: [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[],
        BigNumber[],
        BigNumber[][],
        ([string, number, number] & {
          digest: string;
          hashFunction: number;
          size: number;
        })[]
      ] & {
        collateralToken: string;
        outcomeSlots: BigNumber;
        parentCollectionIndexSet: BigNumber;
        amountSlot: BigNumber;
        partition: BigNumber[];
        recipientAddressSlots: BigNumber[];
        recipientAmountSlots: BigNumber[][];
        outcomeURIs: ([string, number, number] & {
          digest: string;
          hashFunction: number;
          size: number;
        })[];
      };
    }
  >;

  confirmPayouts(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployChild(
    _config: {
      implementation: string;
      keeper: string;
      arbitrator: string;
      timelockSeconds: BigNumberish;
      data: BytesLike;
      ingests: {
        executions: BigNumberish;
        ingestType: BigNumberish;
        slot: BigNumberish;
        solverIndex: BigNumberish;
        data: BytesLike;
      }[];
      conditionBase: {
        collateralToken: string;
        outcomeSlots: BigNumberish;
        parentCollectionIndexSet: BigNumberish;
        amountSlot: BigNumberish;
        partition: BigNumberish[];
        recipientAddressSlots: BigNumberish[];
        recipientAmountSlots: BigNumberish[][];
        outcomeURIs: {
          digest: BytesLike;
          hashFunction: BigNumberish;
          size: BigNumberish;
        }[];
      };
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeSolve(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCallbackOutput(
    _slot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getConditions(
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string, string, BigNumber[], number] & {
      collateralToken: string;
      questionId: string;
      parentCollectionId: string;
      conditionId: string;
      payouts: BigNumber[];
      status: number;
    })[]
  >;

  getData(_slot: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getOutgoingCallbacks(
    slot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  handleCallback(
    _slot: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ingestsValid(overrides?: CallOverrides): Promise<boolean>;

  init(
    _chainParent: string,
    _chainIndex: BigNumberish,
    _solverConfig: {
      implementation: string;
      keeper: string;
      arbitrator: string;
      timelockSeconds: BigNumberish;
      data: BytesLike;
      ingests: {
        executions: BigNumberish;
        ingestType: BigNumberish;
        slot: BigNumberish;
        solverIndex: BigNumberish;
        data: BytesLike;
      }[];
      conditionBase: {
        collateralToken: string;
        outcomeSlots: BigNumberish;
        parentCollectionIndexSet: BigNumberish;
        amountSlot: BigNumberish;
        partition: BigNumberish[];
        recipientAddressSlots: BigNumberish[];
        recipientAmountSlots: BigNumberish[][];
        outcomeURIs: {
          digest: BytesLike;
          hashFunction: BigNumberish;
          size: BigNumberish;
        }[];
      };
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155BatchReceived(
    operator: string,
    from: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    operator: string,
    from: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  percentage(
    x: BigNumberish,
    y: BigNumberish,
    scale: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  prepareSolve(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposePayouts(
    _index: BigNumberish,
    _payouts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  redeemPosition(
    _collateralToken: string,
    _parentCollectionId: BytesLike,
    _conditionId: BytesLike,
    _indexSets: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerOutgoingCallback(
    _slot: BigNumberish,
    _chainIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTrackingId(
    _trackingId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  timelock(overrides?: CallOverrides): Promise<BigNumber>;

  trackingId(overrides?: CallOverrides): Promise<string>;

  uiURI(
    overrides?: CallOverrides
  ): Promise<
    [string, number, number] & {
      digest: string;
      hashFunction: number;
      size: number;
    }
  >;

  callStatic: {
    addData(
      _slot: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addressFromChainIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    arbitrate(
      _index: BigNumberish,
      payouts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    arbitrateNull(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    arbitrationPending(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    arbitrationRequested(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    chainChild(overrides?: CallOverrides): Promise<string>;

    chainIndex(overrides?: CallOverrides): Promise<BigNumber>;

    chainParent(overrides?: CallOverrides): Promise<string>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, number] & {
        collateralToken: string;
        questionId: string;
        parentCollectionId: string;
        conditionId: string;
        status: number;
      }
    >;

    config(
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        string,
        [
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[],
          BigNumber[][],
          ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[]
        ] & {
          collateralToken: string;
          outcomeSlots: BigNumber;
          parentCollectionIndexSet: BigNumber;
          amountSlot: BigNumber;
          partition: BigNumber[];
          recipientAddressSlots: BigNumber[];
          recipientAmountSlots: BigNumber[][];
          outcomeURIs: ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[];
        }
      ] & {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumber;
        data: string;
        conditionBase: [
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[],
          BigNumber[][],
          ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[]
        ] & {
          collateralToken: string;
          outcomeSlots: BigNumber;
          parentCollectionIndexSet: BigNumber;
          amountSlot: BigNumber;
          partition: BigNumber[];
          recipientAddressSlots: BigNumber[];
          recipientAmountSlots: BigNumber[][];
          outcomeURIs: ([string, number, number] & {
            digest: string;
            hashFunction: number;
            size: number;
          })[];
        };
      }
    >;

    confirmPayouts(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deployChild(
      _config: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: CallOverrides
    ): Promise<string>;

    executeSolve(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getCallbackOutput(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getConditions(
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string, string, BigNumber[], number] & {
        collateralToken: string;
        questionId: string;
        parentCollectionId: string;
        conditionId: string;
        payouts: BigNumber[];
        status: number;
      })[]
    >;

    getData(_slot: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getOutgoingCallbacks(
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    handleCallback(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ingestsValid(overrides?: CallOverrides): Promise<boolean>;

    init(
      _chainParent: string,
      _chainIndex: BigNumberish,
      _solverConfig: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: CallOverrides
    ): Promise<void>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    percentage(
      x: BigNumberish,
      y: BigNumberish,
      scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prepareSolve(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    proposePayouts(
      _index: BigNumberish,
      _payouts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    redeemPosition(
      _collateralToken: string,
      _parentCollectionId: BytesLike,
      _conditionId: BytesLike,
      _indexSets: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    registerOutgoingCallback(
      _slot: BigNumberish,
      _chainIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTrackingId(
      _trackingId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    timelock(overrides?: CallOverrides): Promise<BigNumber>;

    trackingId(overrides?: CallOverrides): Promise<string>;

    uiURI(
      overrides?: CallOverrides
    ): Promise<
      [string, number, number] & {
        digest: string;
        hashFunction: number;
        size: number;
      }
    >;
  };

  filters: {
    DeployedChild(
      chainChild?: null
    ): TypedEventFilter<[string], { chainChild: string }>;

    PreparedSolve(
      solver?: null,
      solveIndex?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { solver: string; solveIndex: BigNumber }
    >;
  };

  estimateGas: {
    addData(
      _slot: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addressFromChainIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    arbitrate(
      _index: BigNumberish,
      payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    arbitrateNull(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    arbitrationPending(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    arbitrationRequested(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    chainChild(overrides?: CallOverrides): Promise<BigNumber>;

    chainIndex(overrides?: CallOverrides): Promise<BigNumber>;

    chainParent(overrides?: CallOverrides): Promise<BigNumber>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    confirmPayouts(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployChild(
      _config: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeSolve(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCallbackOutput(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConditions(overrides?: CallOverrides): Promise<BigNumber>;

    getData(_slot: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getOutgoingCallbacks(
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handleCallback(
      _slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ingestsValid(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _chainParent: string,
      _chainIndex: BigNumberish,
      _solverConfig: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    percentage(
      x: BigNumberish,
      y: BigNumberish,
      scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prepareSolve(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposePayouts(
      _index: BigNumberish,
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    redeemPosition(
      _collateralToken: string,
      _parentCollectionId: BytesLike,
      _conditionId: BytesLike,
      _indexSets: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerOutgoingCallback(
      _slot: BigNumberish,
      _chainIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTrackingId(
      _trackingId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    timelock(overrides?: CallOverrides): Promise<BigNumber>;

    trackingId(overrides?: CallOverrides): Promise<BigNumber>;

    uiURI(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addData(
      _slot: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addressFromChainIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    arbitrate(
      _index: BigNumberish,
      payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    arbitrateNull(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    arbitrationPending(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    arbitrationRequested(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    chainChild(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainParent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    confirmPayouts(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployChild(
      _config: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeSolve(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCallbackOutput(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConditions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getData(
      _slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOutgoingCallbacks(
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handleCallback(
      _slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ingestsValid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      _chainParent: string,
      _chainIndex: BigNumberish,
      _solverConfig: {
        implementation: string;
        keeper: string;
        arbitrator: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          ingestType: BigNumberish;
          slot: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          collateralToken: string;
          outcomeSlots: BigNumberish;
          parentCollectionIndexSet: BigNumberish;
          amountSlot: BigNumberish;
          partition: BigNumberish[];
          recipientAddressSlots: BigNumberish[];
          recipientAmountSlots: BigNumberish[][];
          outcomeURIs: {
            digest: BytesLike;
            hashFunction: BigNumberish;
            size: BigNumberish;
          }[];
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    percentage(
      x: BigNumberish,
      y: BigNumberish,
      scale: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    prepareSolve(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposePayouts(
      _index: BigNumberish,
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    redeemPosition(
      _collateralToken: string,
      _parentCollectionId: BytesLike,
      _conditionId: BytesLike,
      _indexSets: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerOutgoingCallback(
      _slot: BigNumberish,
      _chainIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTrackingId(
      _trackingId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    timelock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    trackingId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uiURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
