/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ConditionalTokensEventEmitterInterface
  extends ethers.utils.Interface {
  functions: {};

  events: {
    "ConditionPreparation(bytes32,address,bytes32,uint256)": EventFragment;
    "ConditionResolution(bytes32,address,bytes32,uint256,uint256[])": EventFragment;
    "PayoutRedemption(address,address,bytes32,bytes32,uint256[],uint256)": EventFragment;
    "PositionSplit(address,address,bytes32,bytes32,uint256[],uint256)": EventFragment;
    "PositionsMerge(address,address,bytes32,bytes32,uint256[],uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConditionPreparation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConditionResolution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayoutRedemption"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionSplit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionsMerge"): EventFragment;
}

export class ConditionalTokensEventEmitter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ConditionalTokensEventEmitterInterface;

  functions: {};

  callStatic: {};

  filters: {
    ConditionPreparation(
      conditionId?: BytesLike | null,
      oracle?: string | null,
      questionId?: BytesLike | null,
      outcomeSlotCount?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      {
        conditionId: string;
        oracle: string;
        questionId: string;
        outcomeSlotCount: BigNumber;
      }
    >;

    ConditionResolution(
      conditionId?: BytesLike | null,
      oracle?: string | null,
      questionId?: BytesLike | null,
      outcomeSlotCount?: null,
      payoutNumerators?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber[]],
      {
        conditionId: string;
        oracle: string;
        questionId: string;
        outcomeSlotCount: BigNumber;
        payoutNumerators: BigNumber[];
      }
    >;

    PayoutRedemption(
      redeemer?: string | null,
      collateralToken?: string | null,
      parentCollectionId?: BytesLike | null,
      conditionId?: null,
      indexSets?: null,
      payout?: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber[], BigNumber],
      {
        redeemer: string;
        collateralToken: string;
        parentCollectionId: string;
        conditionId: string;
        indexSets: BigNumber[];
        payout: BigNumber;
      }
    >;

    PositionSplit(
      stakeholder?: string | null,
      collateralToken?: null,
      parentCollectionId?: BytesLike | null,
      conditionId?: BytesLike | null,
      partition?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber[], BigNumber],
      {
        stakeholder: string;
        collateralToken: string;
        parentCollectionId: string;
        conditionId: string;
        partition: BigNumber[];
        amountSlot: BigNumber;
      }
    >;

    PositionsMerge(
      stakeholder?: string | null,
      collateralToken?: null,
      parentCollectionId?: BytesLike | null,
      conditionId?: BytesLike | null,
      partition?: null,
      amount?: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber[], BigNumber],
      {
        stakeholder: string;
        collateralToken: string;
        parentCollectionId: string;
        conditionId: string;
        partition: BigNumber[];
        amountSlot: BigNumber;
      }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
