/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SolutionsHubInterface extends ethers.utils.Interface {
  functions: {
    "conditionalTokens()": FunctionFragment;
    "createSolution(address,tuple[])": FunctionFragment;
    "executeSolution(bytes32,bytes32)": FunctionFragment;
    "getSolution(bytes32)": FunctionFragment;
    "linkToProposal(bytes32,bytes32)": FunctionFragment;
    "setSolverConfigs(bytes32,tuple[])": FunctionFragment;
    "solverFromIndex(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "conditionalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSolution",
    values: [
      string,
      {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSolution",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSolution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "linkToProposal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSolverConfigs",
    values: [
      BytesLike,
      {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "solverFromIndex",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "conditionalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkToProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSolverConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solverFromIndex",
    data: BytesLike
  ): Result;

  events: {
    "CreateSolution(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreateSolution"): EventFragment;
}

export class SolutionsHub extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SolutionsHubInterface;

  functions: {
    conditionalTokens(overrides?: CallOverrides): Promise<[string]>;

    createSolution(
      _collateralToken: string,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeSolution(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getSolution(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          boolean,
          string,
          string,
          string,
          string,
          string,
          ([
            string,
            string,
            string,
            BigNumber,
            string,
            ([string, boolean, boolean, BigNumber, BigNumber, string] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[]
          ] & {
            factory: string;
            keeper: string;
            arbiter: string;
            timelockHours: BigNumber;
            data: string;
            actions: ([
              string,
              boolean,
              boolean,
              BigNumber,
              BigNumber,
              string
            ] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[];
          })[],
          string[]
        ] & {
          executed: boolean;
          collateralToken: string;
          keeper: string;
          proposalHub: string;
          proposalId: string;
          id: string;
          solverConfigs: ([
            string,
            string,
            string,
            BigNumber,
            string,
            ([string, boolean, boolean, BigNumber, BigNumber, string] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[]
          ] & {
            factory: string;
            keeper: string;
            arbiter: string;
            timelockHours: BigNumber;
            data: string;
            actions: ([
              string,
              boolean,
              boolean,
              BigNumber,
              BigNumber,
              string
            ] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[];
          })[];
          solverAddresses: string[];
        }
      ] & {
        solution: [
          boolean,
          string,
          string,
          string,
          string,
          string,
          ([
            string,
            string,
            string,
            BigNumber,
            string,
            ([string, boolean, boolean, BigNumber, BigNumber, string] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[]
          ] & {
            factory: string;
            keeper: string;
            arbiter: string;
            timelockHours: BigNumber;
            data: string;
            actions: ([
              string,
              boolean,
              boolean,
              BigNumber,
              BigNumber,
              string
            ] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[];
          })[],
          string[]
        ] & {
          executed: boolean;
          collateralToken: string;
          keeper: string;
          proposalHub: string;
          proposalId: string;
          id: string;
          solverConfigs: ([
            string,
            string,
            string,
            BigNumber,
            string,
            ([string, boolean, boolean, BigNumber, BigNumber, string] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[]
          ] & {
            factory: string;
            keeper: string;
            arbiter: string;
            timelockHours: BigNumber;
            data: string;
            actions: ([
              string,
              boolean,
              boolean,
              BigNumber,
              BigNumber,
              string
            ] & {
              to: string;
              executed: boolean;
              useSolverIdx: boolean;
              solverIdx: BigNumber;
              value: BigNumber;
              data: string;
            })[];
          })[];
          solverAddresses: string[];
        };
      }
    >;

    linkToProposal(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSolverConfigs(
      _solutionId: BytesLike,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    solverFromIndex(
      _solutionId: BytesLike,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { solver: string }>;
  };

  conditionalTokens(overrides?: CallOverrides): Promise<string>;

  createSolution(
    _collateralToken: string,
    _solverConfigs: {
      factory: string;
      keeper: string;
      arbiter: string;
      timelockHours: BigNumberish;
      data: BytesLike;
      actions: {
        to: string;
        executed: boolean;
        useSolverIdx: boolean;
        solverIdx: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      }[];
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeSolution(
    _proposalId: BytesLike,
    _solutionId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getSolution(
    _id: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      string,
      string,
      string,
      string,
      string,
      ([
        string,
        string,
        string,
        BigNumber,
        string,
        ([string, boolean, boolean, BigNumber, BigNumber, string] & {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumber;
          value: BigNumber;
          data: string;
        })[]
      ] & {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumber;
        data: string;
        actions: ([string, boolean, boolean, BigNumber, BigNumber, string] & {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumber;
          value: BigNumber;
          data: string;
        })[];
      })[],
      string[]
    ] & {
      executed: boolean;
      collateralToken: string;
      keeper: string;
      proposalHub: string;
      proposalId: string;
      id: string;
      solverConfigs: ([
        string,
        string,
        string,
        BigNumber,
        string,
        ([string, boolean, boolean, BigNumber, BigNumber, string] & {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumber;
          value: BigNumber;
          data: string;
        })[]
      ] & {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumber;
        data: string;
        actions: ([string, boolean, boolean, BigNumber, BigNumber, string] & {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumber;
          value: BigNumber;
          data: string;
        })[];
      })[];
      solverAddresses: string[];
    }
  >;

  linkToProposal(
    _proposalId: BytesLike,
    _solutionId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSolverConfigs(
    _solutionId: BytesLike,
    _solverConfigs: {
      factory: string;
      keeper: string;
      arbiter: string;
      timelockHours: BigNumberish;
      data: BytesLike;
      actions: {
        to: string;
        executed: boolean;
        useSolverIdx: boolean;
        solverIdx: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      }[];
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  solverFromIndex(
    _solutionId: BytesLike,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    conditionalTokens(overrides?: CallOverrides): Promise<string>;

    createSolution(
      _collateralToken: string,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: CallOverrides
    ): Promise<string>;

    executeSolution(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getSolution(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        string,
        string,
        string,
        string,
        string,
        ([
          string,
          string,
          string,
          BigNumber,
          string,
          ([string, boolean, boolean, BigNumber, BigNumber, string] & {
            to: string;
            executed: boolean;
            useSolverIdx: boolean;
            solverIdx: BigNumber;
            value: BigNumber;
            data: string;
          })[]
        ] & {
          factory: string;
          keeper: string;
          arbiter: string;
          timelockHours: BigNumber;
          data: string;
          actions: ([string, boolean, boolean, BigNumber, BigNumber, string] & {
            to: string;
            executed: boolean;
            useSolverIdx: boolean;
            solverIdx: BigNumber;
            value: BigNumber;
            data: string;
          })[];
        })[],
        string[]
      ] & {
        executed: boolean;
        collateralToken: string;
        keeper: string;
        proposalHub: string;
        proposalId: string;
        id: string;
        solverConfigs: ([
          string,
          string,
          string,
          BigNumber,
          string,
          ([string, boolean, boolean, BigNumber, BigNumber, string] & {
            to: string;
            executed: boolean;
            useSolverIdx: boolean;
            solverIdx: BigNumber;
            value: BigNumber;
            data: string;
          })[]
        ] & {
          factory: string;
          keeper: string;
          arbiter: string;
          timelockHours: BigNumber;
          data: string;
          actions: ([string, boolean, boolean, BigNumber, BigNumber, string] & {
            to: string;
            executed: boolean;
            useSolverIdx: boolean;
            solverIdx: BigNumber;
            value: BigNumber;
            data: string;
          })[];
        })[];
        solverAddresses: string[];
      }
    >;

    linkToProposal(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setSolverConfigs(
      _solutionId: BytesLike,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    solverFromIndex(
      _solutionId: BytesLike,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    CreateSolution(id?: null): TypedEventFilter<[string], { id: string }>;
  };

  estimateGas: {
    conditionalTokens(overrides?: CallOverrides): Promise<BigNumber>;

    createSolution(
      _collateralToken: string,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeSolution(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getSolution(_id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    linkToProposal(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSolverConfigs(
      _solutionId: BytesLike,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    solverFromIndex(
      _solutionId: BytesLike,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    conditionalTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createSolution(
      _collateralToken: string,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeSolution(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getSolution(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    linkToProposal(
      _proposalId: BytesLike,
      _solutionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSolverConfigs(
      _solutionId: BytesLike,
      _solverConfigs: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockHours: BigNumberish;
        data: BytesLike;
        actions: {
          to: string;
          executed: boolean;
          useSolverIdx: boolean;
          solverIdx: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    solverFromIndex(
      _solutionId: BytesLike,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
