/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SolverInterface extends ethers.utils.Interface {
  functions: {
    "addData(uint8,uint256,bytes)": FunctionFragment;
    "addressPort(uint256)": FunctionFragment;
    "allocatePartition()": FunctionFragment;
    "arbitrate(uint256[])": FunctionFragment;
    "arbitrationDelivered()": FunctionFragment;
    "boolPort(uint256)": FunctionFragment;
    "bytes32Port(uint256)": FunctionFragment;
    "bytesPort(uint256)": FunctionFragment;
    "collateralToken()": FunctionFragment;
    "conditionalTokens()": FunctionFragment;
    "conditions(uint256)": FunctionFragment;
    "config()": FunctionFragment;
    "confirmPayouts()": FunctionFragment;
    "deferredIngestsValid()": FunctionFragment;
    "executeSolve()": FunctionFragment;
    "executed()": FunctionFragment;
    "getCanonCollectionId(uint256)": FunctionFragment;
    "getOutput(uint256,uint256)": FunctionFragment;
    "getPayouts()": FunctionFragment;
    "handleShallowPosition()": FunctionFragment;
    "ingest(uint256)": FunctionFragment;
    "init(address,bytes32,address,address,tuple)": FunctionFragment;
    "lockedPorts(uint256,uint256)": FunctionFragment;
    "nullArbitrate()": FunctionFragment;
    "numConditions()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "pendingArbitration()": FunctionFragment;
    "portVersions(uint256,uint256)": FunctionFragment;
    "prepareCondition()": FunctionFragment;
    "prepareSolve()": FunctionFragment;
    "proposalsHub()": FunctionFragment;
    "proposePayouts(uint256[])": FunctionFragment;
    "solutionId()": FunctionFragment;
    "solutionsHub()": FunctionFragment;
    "solved()": FunctionFragment;
    "solverAddressFromIndex(uint256)": FunctionFragment;
    "splitPosition()": FunctionFragment;
    "staticcallSolver(uint256,bytes)": FunctionFragment;
    "timelock()": FunctionFragment;
    "uint256Port(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addData",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addressPort",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocatePartition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrate",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrationDelivered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "boolPort",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32Port",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bytesPort",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conditionalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conditions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmPayouts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deferredIngestsValid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSolve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "executed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCanonCollectionId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayouts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleShallowPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ingest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [
      string,
      BytesLike,
      string,
      string,
      {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          deferred: boolean;
          isConstant: boolean;
          port: BigNumberish;
          key: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        actions: {
          executed: boolean;
          isPort: boolean;
          to: string;
          portIndex: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          outcomeSlots: BigNumberish;
          parentCollectionPartitionIndex: BigNumberish;
          amount: BigNumberish;
          partition: BigNumberish[];
          recipientAddressPorts: BigNumberish[][];
          recipientAmounts: BigNumberish[][];
          metadata: string;
        };
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedPorts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nullArbitrate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numConditions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingArbitration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "portVersions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareCondition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "prepareSolve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalsHub",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposePayouts",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "solutionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "solutionsHub",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "solved", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "solverAddressFromIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "splitPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "staticcallSolver",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uint256Port",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressPort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocatePartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbitrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "arbitrationDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "boolPort", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bytes32Port",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bytesPort", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "conditions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deferredIngestsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCanonCollectionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOutput", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPayouts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleShallowPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ingest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedPorts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullArbitrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingArbitration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "portVersions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareSolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalsHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposePayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solutionId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "solutionsHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "solverAddressFromIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "staticcallSolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uint256Port",
    data: BytesLike
  ): Result;

  events: {};
}

export class Solver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SolverInterface;

  functions: {
    addData(
      _port: BigNumberish,
      _key: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addressPort(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    allocatePartition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    arbitrate(
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    arbitrationDelivered(overrides?: CallOverrides): Promise<[boolean]>;

    boolPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>;

    bytes32Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytesPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    collateralToken(overrides?: CallOverrides): Promise<[string]>;

    conditionalTokens(overrides?: CallOverrides): Promise<[string]>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, string, string] & {
        reported: boolean;
        questionId: string;
        parentCollectionId: string;
        conditionId: string;
      }
    >;

    config(
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        string,
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[][],
          BigNumber[][],
          string
        ] & {
          outcomeSlots: BigNumber;
          parentCollectionPartitionIndex: BigNumber;
          amount: BigNumber;
          partition: BigNumber[];
          recipientAddressPorts: BigNumber[][];
          recipientAmounts: BigNumber[][];
          metadata: string;
        }
      ] & {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumber;
        data: string;
        conditionBase: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[][],
          BigNumber[][],
          string
        ] & {
          outcomeSlots: BigNumber;
          parentCollectionPartitionIndex: BigNumber;
          amount: BigNumber;
          partition: BigNumber[];
          recipientAddressPorts: BigNumber[][];
          recipientAmounts: BigNumber[][];
          metadata: string;
        };
      }
    >;

    confirmPayouts(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deferredIngestsValid(overrides?: CallOverrides): Promise<[boolean]>;

    executeSolve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executed(overrides?: CallOverrides): Promise<[boolean]>;

    getCanonCollectionId(
      _partitionIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _id: string }>;

    getOutput(
      _port: BigNumberish,
      _key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { data: string }>;

    getPayouts(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    handleShallowPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ingest(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    init(
      _collateralToken: string,
      _solutionId: BytesLike,
      _proposalsHub: string,
      _solutionsHub: string,
      _solverConfig: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          deferred: boolean;
          isConstant: boolean;
          port: BigNumberish;
          key: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        actions: {
          executed: boolean;
          isPort: boolean;
          to: string;
          portIndex: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          outcomeSlots: BigNumberish;
          parentCollectionPartitionIndex: BigNumberish;
          amount: BigNumberish;
          partition: BigNumberish[];
          recipientAddressPorts: BigNumberish[][];
          recipientAmounts: BigNumberish[][];
          metadata: string;
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockedPorts(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    nullArbitrate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    numConditions(overrides?: CallOverrides): Promise<[BigNumber]>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pendingArbitration(overrides?: CallOverrides): Promise<[boolean]>;

    portVersions(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    prepareCondition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    prepareSolve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposalsHub(overrides?: CallOverrides): Promise<[string]>;

    proposePayouts(
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    solutionId(overrides?: CallOverrides): Promise<[string]>;

    solutionsHub(overrides?: CallOverrides): Promise<[string]>;

    solved(overrides?: CallOverrides): Promise<[boolean]>;

    solverAddressFromIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _address: string }>;

    splitPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    staticcallSolver(
      _solverIndex: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    timelock(overrides?: CallOverrides): Promise<[BigNumber]>;

    uint256Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  addData(
    _port: BigNumberish,
    _key: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addressPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  allocatePartition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  arbitrate(
    _payouts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  arbitrationDelivered(overrides?: CallOverrides): Promise<boolean>;

  boolPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  bytes32Port(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  bytesPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  collateralToken(overrides?: CallOverrides): Promise<string>;

  conditionalTokens(overrides?: CallOverrides): Promise<string>;

  conditions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, string, string] & {
      reported: boolean;
      questionId: string;
      parentCollectionId: string;
      conditionId: string;
    }
  >;

  config(
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      string,
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[],
        BigNumber[][],
        BigNumber[][],
        string
      ] & {
        outcomeSlots: BigNumber;
        parentCollectionPartitionIndex: BigNumber;
        amount: BigNumber;
        partition: BigNumber[];
        recipientAddressPorts: BigNumber[][];
        recipientAmounts: BigNumber[][];
        metadata: string;
      }
    ] & {
      factory: string;
      keeper: string;
      arbiter: string;
      timelockSeconds: BigNumber;
      data: string;
      conditionBase: [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[],
        BigNumber[][],
        BigNumber[][],
        string
      ] & {
        outcomeSlots: BigNumber;
        parentCollectionPartitionIndex: BigNumber;
        amount: BigNumber;
        partition: BigNumber[];
        recipientAddressPorts: BigNumber[][];
        recipientAmounts: BigNumber[][];
        metadata: string;
      };
    }
  >;

  confirmPayouts(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deferredIngestsValid(overrides?: CallOverrides): Promise<boolean>;

  executeSolve(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executed(overrides?: CallOverrides): Promise<boolean>;

  getCanonCollectionId(
    _partitionIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getOutput(
    _port: BigNumberish,
    _key: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getPayouts(overrides?: CallOverrides): Promise<BigNumber[]>;

  handleShallowPosition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ingest(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  init(
    _collateralToken: string,
    _solutionId: BytesLike,
    _proposalsHub: string,
    _solutionsHub: string,
    _solverConfig: {
      factory: string;
      keeper: string;
      arbiter: string;
      timelockSeconds: BigNumberish;
      data: BytesLike;
      ingests: {
        executions: BigNumberish;
        deferred: boolean;
        isConstant: boolean;
        port: BigNumberish;
        key: BigNumberish;
        solverIndex: BigNumberish;
        data: BytesLike;
      }[];
      actions: {
        executed: boolean;
        isPort: boolean;
        to: string;
        portIndex: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      }[];
      conditionBase: {
        outcomeSlots: BigNumberish;
        parentCollectionPartitionIndex: BigNumberish;
        amount: BigNumberish;
        partition: BigNumberish[];
        recipientAddressPorts: BigNumberish[][];
        recipientAmounts: BigNumberish[][];
        metadata: string;
      };
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockedPorts(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nullArbitrate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  numConditions(overrides?: CallOverrides): Promise<BigNumber>;

  onERC1155BatchReceived(
    operator: string,
    from: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    operator: string,
    from: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pendingArbitration(overrides?: CallOverrides): Promise<boolean>;

  portVersions(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  prepareCondition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  prepareSolve(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposalsHub(overrides?: CallOverrides): Promise<string>;

  proposePayouts(
    _payouts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  solutionId(overrides?: CallOverrides): Promise<string>;

  solutionsHub(overrides?: CallOverrides): Promise<string>;

  solved(overrides?: CallOverrides): Promise<boolean>;

  solverAddressFromIndex(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  splitPosition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  staticcallSolver(
    _solverIndex: BigNumberish,
    _data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  timelock(overrides?: CallOverrides): Promise<BigNumber>;

  uint256Port(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    addData(
      _port: BigNumberish,
      _key: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addressPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    allocatePartition(overrides?: CallOverrides): Promise<void>;

    arbitrate(
      _payouts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    arbitrationDelivered(overrides?: CallOverrides): Promise<boolean>;

    boolPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    bytes32Port(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    bytesPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    collateralToken(overrides?: CallOverrides): Promise<string>;

    conditionalTokens(overrides?: CallOverrides): Promise<string>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, string, string] & {
        reported: boolean;
        questionId: string;
        parentCollectionId: string;
        conditionId: string;
      }
    >;

    config(
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        string,
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[][],
          BigNumber[][],
          string
        ] & {
          outcomeSlots: BigNumber;
          parentCollectionPartitionIndex: BigNumber;
          amount: BigNumber;
          partition: BigNumber[];
          recipientAddressPorts: BigNumber[][];
          recipientAmounts: BigNumber[][];
          metadata: string;
        }
      ] & {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumber;
        data: string;
        conditionBase: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          BigNumber[][],
          BigNumber[][],
          string
        ] & {
          outcomeSlots: BigNumber;
          parentCollectionPartitionIndex: BigNumber;
          amount: BigNumber;
          partition: BigNumber[];
          recipientAddressPorts: BigNumber[][];
          recipientAmounts: BigNumber[][];
          metadata: string;
        };
      }
    >;

    confirmPayouts(overrides?: CallOverrides): Promise<void>;

    deferredIngestsValid(overrides?: CallOverrides): Promise<boolean>;

    executeSolve(overrides?: CallOverrides): Promise<void>;

    executed(overrides?: CallOverrides): Promise<boolean>;

    getCanonCollectionId(
      _partitionIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getOutput(
      _port: BigNumberish,
      _key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getPayouts(overrides?: CallOverrides): Promise<BigNumber[]>;

    handleShallowPosition(overrides?: CallOverrides): Promise<void>;

    ingest(_index: BigNumberish, overrides?: CallOverrides): Promise<void>;

    init(
      _collateralToken: string,
      _solutionId: BytesLike,
      _proposalsHub: string,
      _solutionsHub: string,
      _solverConfig: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          deferred: boolean;
          isConstant: boolean;
          port: BigNumberish;
          key: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        actions: {
          executed: boolean;
          isPort: boolean;
          to: string;
          portIndex: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          outcomeSlots: BigNumberish;
          parentCollectionPartitionIndex: BigNumberish;
          amount: BigNumberish;
          partition: BigNumberish[];
          recipientAddressPorts: BigNumberish[][];
          recipientAmounts: BigNumberish[][];
          metadata: string;
        };
      },
      overrides?: CallOverrides
    ): Promise<void>;

    lockedPorts(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nullArbitrate(overrides?: CallOverrides): Promise<void>;

    numConditions(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    pendingArbitration(overrides?: CallOverrides): Promise<boolean>;

    portVersions(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prepareCondition(overrides?: CallOverrides): Promise<void>;

    prepareSolve(overrides?: CallOverrides): Promise<void>;

    proposalsHub(overrides?: CallOverrides): Promise<string>;

    proposePayouts(
      _payouts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    solutionId(overrides?: CallOverrides): Promise<string>;

    solutionsHub(overrides?: CallOverrides): Promise<string>;

    solved(overrides?: CallOverrides): Promise<boolean>;

    solverAddressFromIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    splitPosition(overrides?: CallOverrides): Promise<void>;

    staticcallSolver(
      _solverIndex: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    timelock(overrides?: CallOverrides): Promise<BigNumber>;

    uint256Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addData(
      _port: BigNumberish,
      _key: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addressPort(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allocatePartition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    arbitrate(
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    arbitrationDelivered(overrides?: CallOverrides): Promise<BigNumber>;

    boolPort(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    bytes32Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytesPort(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateralToken(overrides?: CallOverrides): Promise<BigNumber>;

    conditionalTokens(overrides?: CallOverrides): Promise<BigNumber>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    confirmPayouts(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deferredIngestsValid(overrides?: CallOverrides): Promise<BigNumber>;

    executeSolve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executed(overrides?: CallOverrides): Promise<BigNumber>;

    getCanonCollectionId(
      _partitionIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOutput(
      _port: BigNumberish,
      _key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPayouts(overrides?: CallOverrides): Promise<BigNumber>;

    handleShallowPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ingest(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    init(
      _collateralToken: string,
      _solutionId: BytesLike,
      _proposalsHub: string,
      _solutionsHub: string,
      _solverConfig: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          deferred: boolean;
          isConstant: boolean;
          port: BigNumberish;
          key: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        actions: {
          executed: boolean;
          isPort: boolean;
          to: string;
          portIndex: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          outcomeSlots: BigNumberish;
          parentCollectionPartitionIndex: BigNumberish;
          amount: BigNumberish;
          partition: BigNumberish[];
          recipientAddressPorts: BigNumberish[][];
          recipientAmounts: BigNumberish[][];
          metadata: string;
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockedPorts(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nullArbitrate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    numConditions(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pendingArbitration(overrides?: CallOverrides): Promise<BigNumber>;

    portVersions(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prepareCondition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    prepareSolve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposalsHub(overrides?: CallOverrides): Promise<BigNumber>;

    proposePayouts(
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    solutionId(overrides?: CallOverrides): Promise<BigNumber>;

    solutionsHub(overrides?: CallOverrides): Promise<BigNumber>;

    solved(overrides?: CallOverrides): Promise<BigNumber>;

    solverAddressFromIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    splitPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    staticcallSolver(
      _solverIndex: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    timelock(overrides?: CallOverrides): Promise<BigNumber>;

    uint256Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addData(
      _port: BigNumberish,
      _key: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addressPort(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allocatePartition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    arbitrate(
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    arbitrationDelivered(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    boolPort(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytes32Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytesPort(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    conditionalTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    confirmPayouts(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deferredIngestsValid(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executeSolve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCanonCollectionId(
      _partitionIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOutput(
      _port: BigNumberish,
      _key: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPayouts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    handleShallowPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ingest(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    init(
      _collateralToken: string,
      _solutionId: BytesLike,
      _proposalsHub: string,
      _solutionsHub: string,
      _solverConfig: {
        factory: string;
        keeper: string;
        arbiter: string;
        timelockSeconds: BigNumberish;
        data: BytesLike;
        ingests: {
          executions: BigNumberish;
          deferred: boolean;
          isConstant: boolean;
          port: BigNumberish;
          key: BigNumberish;
          solverIndex: BigNumberish;
          data: BytesLike;
        }[];
        actions: {
          executed: boolean;
          isPort: boolean;
          to: string;
          portIndex: BigNumberish;
          value: BigNumberish;
          data: BytesLike;
        }[];
        conditionBase: {
          outcomeSlots: BigNumberish;
          parentCollectionPartitionIndex: BigNumberish;
          amount: BigNumberish;
          partition: BigNumberish[];
          recipientAddressPorts: BigNumberish[][];
          recipientAmounts: BigNumberish[][];
          metadata: string;
        };
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockedPorts(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nullArbitrate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    numConditions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      operator: string,
      from: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pendingArbitration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    portVersions(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    prepareCondition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    prepareSolve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposalsHub(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposePayouts(
      _payouts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    solutionId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    solutionsHub(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    solved(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    solverAddressFromIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    splitPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    staticcallSolver(
      _solverIndex: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    timelock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uint256Port(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
