/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SolverFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createSolver(address,address,uint256,tuple[],bytes)": FunctionFragment;
    "solverAddresses(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createSolver",
    values: [
      string,
      string,
      BigNumberish,
      { value: BigNumberish; to: string; executed: boolean; data: BytesLike }[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "solverAddresses",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solverAddresses",
    data: BytesLike
  ): Result;

  events: {
    "SolverCreated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SolverCreated"): EventFragment;
}

export class SolverFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SolverFactoryInterface;

  functions: {
    createSolver(
      _keeper: string,
      _arbiter: string,
      _timelockHours: BigNumberish,
      _actions: {
        value: BigNumberish;
        to: string;
        executed: boolean;
        data: BytesLike;
      }[],
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    solverAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createSolver(
    _keeper: string,
    _arbiter: string,
    _timelockHours: BigNumberish,
    _actions: {
      value: BigNumberish;
      to: string;
      executed: boolean;
      data: BytesLike;
    }[],
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  solverAddresses(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createSolver(
      _keeper: string,
      _arbiter: string,
      _timelockHours: BigNumberish,
      _actions: {
        value: BigNumberish;
        to: string;
        executed: boolean;
        data: BytesLike;
      }[],
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    solverAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    SolverCreated(
      solver?: null
    ): TypedEventFilter<[string], { solver: string }>;
  };

  estimateGas: {
    createSolver(
      _keeper: string,
      _arbiter: string,
      _timelockHours: BigNumberish,
      _actions: {
        value: BigNumberish;
        to: string;
        executed: boolean;
        data: BytesLike;
      }[],
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    solverAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createSolver(
      _keeper: string,
      _arbiter: string,
      _timelockHours: BigNumberish,
      _actions: {
        value: BigNumberish;
        to: string;
        executed: boolean;
        data: BytesLike;
      }[],
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    solverAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
